version: '3'

services:
  app:
    image: 'postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
       - db


  db:
    image: 'postgres:latest'
    container_name: qs3
    environment:
       - POSTGRES_USER=compose-postgres
       - POSTGRES_PASSWORD=compose-postgres
       - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./daabase/createDatabase.sql